[package]
name = "firebaserust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.9.1"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }